# This project is intended to have a local database container in development
# environment and a cloud database instance in production.
version: '3.9'

services:
  web:
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
